[package]
name = "zana"
version = "0.1.0"
edition = "2021"

[lib]
name = "zana"
path = "src/lib.rs" # Ensures the library is correctly defined

[dependencies]
rand = "0.8"
ndarray = "0.15"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
num-complex = "0.4.6"
